### PR TITLE
fix: build anno relies on utr/cds ordering

### LINKED ISSUE #135: Error on importing gencode anno with out of order UTR/CDS
On trying to build [gencode.v47lift37](https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_47/GRCh37_mapping/gencode.v47lift37.annotation.gff3.gz), got an error:
```
>>> gk.GenomeAnnotation.build_gencode("v47lift37.gff3.gz", "gencode.v47lift37", gk.Genome("hg19"))
Loading v47lift37.basic.gff3.gz...
Unknown GFF type=start_codon on line 173.
Unknown GFF type=stop_codon on line 176.
utr3: chr1:139309-139378:-:hg19
utr3:chr1:137620-138528:-:hg19
utr3:chr1:134900-135801:-:hg19
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: src/genome_anno_io.cpp:566: In GFF3 file: v47lift37.basic.gff3.gz:202
  src/genome_anno_io.cpp:630: Expected unique UTR3 per exon for UTR3 chr1:137620-138528:-:hg19.
```

The problem is in this transcript:
```
chr1    ENSEMBL gene    134901  139379  .       -       .       ID=ENSG00000237683.5;gene_id=ENSG00000237683.5;gene_type=protein_coding;gene_status=KNOWN;gene_name=AL627309.1;level=3;remap_substituted_missing_target=V19
chr1    ENSEMBL transcript      134901  139379  .       -       .       ID=ENST00000423372.3;Parent=ENSG00000237683.5;gene_id=ENSG00000237683.5;transcript_id=ENST00000423372.3;gene_type=protein_coding;gene_status=KNOWN;gene_name=AL627309.1;transcript_type=protein_coding;transcript_status=KNOWN;transcript_name=AL627309.1-201;level=3;protein_id=ENSP00000473460.1;tag=basic,appris_principal;remap_substituted_missing_target=V19
chr1    ENSEMBL exon    137621  139379  .       -       .       ID=exon:ENST00000423372.3:1;Parent=ENST00000423372.3;gene_id=ENSG00000237683.5;transcript_id=ENST00000423372.3;gene_type=protein_coding;gene_status=KNOWN;gene_name=AL627309.1;transcript_type=protein_coding;transcript_status=KNOWN;transcript_name=AL627309.1-201;exon_number=1;exon_id=ENSE00002221580.1;level=3;protein_id=ENSP00000473460.1;tag=basic,appris_principal;remap_substituted_missing_target=V19
chr1    ENSEMBL UTR     139310  139379  .       -       .       ID=UTR:ENST00000423372.3:1;Parent=ENST00000423372.3;gene_id=ENSG00000237683.5;transcript_id=ENST00000423372.3;gene_type=protein_coding;gene_status=KNOWN;gene_name=AL627309.1;transcript_type=protein_coding;transcript_status=KNOWN;transcript_name=AL627309.1-201;level=3;protein_id=ENSP00000473460.1;tag=basic,appris_principal;remap_substituted_missing_target=V19
chr1    ENSEMBL CDS     138530  139309  .       -       0       ID=CDS:ENST00000423372.3:1;Parent=ENST00000423372.3;gene_id=ENSG00000237683.5;transcript_id=ENST00000423372.3;gene_type=protein_coding;gene_status=KNOWN;gene_name=AL627309.1;transcript_type=protein_coding;transcript_status=KNOWN;transcript_name=AL627309.1-201;exon_number=1;exon_id=ENSE00002221580.1;level=3;protein_id=ENSP00000473460.1;tag=basic,appris_principal;remap_substituted_missing_target=V19
chr1    ENSEMBL stop_codon      138530  138532  .       -       0       ID=stop_codon:ENST00000423372.3:1;Parent=ENST00000423372.3;gene_id=ENSG00000237683.5;transcript_id=ENST00000423372.3;gene_type=protein_coding;gene_status=KNOWN;gene_name=AL627309.1;transcript_type=protein_coding;transcript_status=KNOWN;transcript_name=AL627309.1-201;exon_number=1;exon_id=ENSE00002221580.1;level=3;protein_id=ENSP00000473460.1;tag=basic,appris_principal;remap_substituted_missing_target=V19
chr1    ENSEMBL UTR     137621  138529  .       -       .       ID=UTR:ENST00000423372.3:1;Parent=ENST00000423372.3;gene_id=ENSG00000237683.5;transcript_id=ENST00000423372.3;gene_type=protein_coding;gene_status=KNOWN;gene_name=AL627309.1;transcript_type=protein_coding;transcript_status=KNOWN;transcript_name=AL627309.1-201;level=3;protein_id=ENSP00000473460.1;tag=basic,appris_principal;remap_substituted_missing_target=V19
chr1    ENSEMBL exon    134901  135802  .       -       .       ID=exon:ENST00000423372.3:2;Parent=ENST00000423372.3;gene_id=ENSG00000237683.5;transcript_id=ENST00000423372.3;gene_type=protein_coding;gene_status=KNOWN;gene_name=AL627309.1;transcript_type=protein_coding;transcript_status=KNOWN;transcript_name=AL627309.1-201;exon_number=2;exon_id=ENSE00002314092.1;level=3;protein_id=ENSP00000473460.1;tag=basic,appris_principal;remap_substituted_missing_target=V19
chr1    ENSEMBL UTR     134901  135802  .       -       .       ID=UTR:ENST00000423372.3:3;Parent=ENST00000423372.3;gene_id=ENSG00000237683.5;transcript_id=ENST00000423372.3;gene_type=protein_coding;gene_status=KNOWN;gene_name=AL627309.1;transcript_type=protein_coding;transcript_status=KNOWN;transcript_name=AL627309.1-201;level=3;protein_id=ENSP00000473460.1;tag=basic,appris_principal;remap_substituted_missing_target=V19
```

The code misidentifies utr5 (139309-139378) as a utr3. The [implicit assumption in our code](https://github.com/deepgenomics/GenomeKit/blob/2f85841c39c48a206efb18d9dd7eec67ce522047/src/genome_anno_io.cpp#L526) is that if a UTR appears before any CDSs on the negative strand then it is a utr3. This causes 2 utr3s to be associated with the first exon.

### PR DESCRIPTION
**Pull request by nahshon-weissberg**
fixes #135

### CODE REVIEW

File: src/genome_anno_io.cpp [hunk 1]
```diff
@@ -669,17 +638,33 @@ class genome_anno::builder {
...
 
+		sort(begin(cdss_to_link), end(cdss_to_link), upstream_ordering);
+
+		for (packed_utr& utr : generic_utrs_to_link) {
+			const packed_cds first_cds = cdss_to_link.front();
+			const packed_cds last_cds = cdss_to_link.back();
+			GK_CHECK(utr.upstream_of(first_cds) || utr.dnstream_of(last_cds), value,
+				"Found utr {} in middle of cds", utr);
+			if (utr.upstream_of(first_cds)) {
+				utr5s_to_link.push_back(utr);
```
Comment (s22chan) [inline src/genome_anno_io.cpp:660]: does `utr5s_to_link` require some kind of ordering to be maintained?  eg, if `utr5s_to_link` and `generic_utrs_to_link` were not empty, is push_back correct?

Comment (nahshon-weissberg) [reply src/genome_anno_io.cpp:660]: As far as I can tell ordering does not have to be maintained here. 

An area where this may seem problematic is in linking the utr5s and utr3s to the respective exons on 686-688, in which case sorting the `utr5s_to_link` and `utr3s_to_link` might be necessary. However this sorting is done in the `link_exonic_elements` function on 623, so there is no problem there. 

Additionally, the `needs_remap` bool that is passed to `link_exonic_elements` I believe does not rely on an ordered `utr5s_to_link` and `utr3s_to_link` as `exon_start`/`exon_stop` that are used to set `needs_remap` themselves do not rely on those vectors being ordered. 

Please let me know if you think there is an oversight here.

**Review by s22chan — APPROVED** [review]
Thank you! Nice first contribution!
