### PR TITLE
fix: check genome.dna(Interval) arg type

### LINKED ISSUE #67: No type check on genome.dna(Interval)
Getting this cryptic error instead:
```
>>> import genome_kit as gk
>>> genome = gk.Genome("hg38")
>>> genome.dna(0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: src/py_init.cpp:72: Traceback (most recent call last):
  File "redacted.../python3.10/site-packages/genome_kit/gk_data.py",
 line 87, in resolve_datafile_path
  ¦ path = get_file(rel_path)
  File "redacted.../python3.10/site-packages/genome_kit/gk_data.py",
 line 53, in get_file
  ¦ return data_manager.get_file(filename)
  File "redacted.../python3.10/site-packages/gk_dg_plugins/data_mana
ger.py", line 124, in get_file
  ¦ raise ValueError(f"No such file: {filename}")
ValueError: No such file: 2551.hash
```

### PR DESCRIPTION
**Pull request by ovesh**
fixes #67

### CODE REVIEW

File: src/py_genome_dna.cpp [hunk 1]
```diff
@@ -64,6 +64,9 @@ GKPY_OMETHOD_BEGIN(GenomeDNA, Call)
 	if (!PyArg_ParseTupleAndKeywords(args, kwds, "O|p", arg_names, &interval_arg, &allow_outside_chromosome))
 		 return nullptr;
 
+	if (!PyInterval::check(interval_arg)) {
+		GK_THROW(type, "Expected argument of type Interval");
+	}
 	// Extract DNA for an Interval arg
 	const interval_t& c = ((PyInterval*)interval_arg)->value();
```
Comment (s22chan) [inline src/py_genome_dna.cpp:71]: Might as well use the helper

```suggestion
	// Extract DNA for an Interval arg
	interval_t c = PyAsInterval(interval_arg);
```

**Review by s22chan — APPROVED** [review]

File: src/py_genome_dna.cpp (hunk 1 above)
Comment (ovesh) [reply src/py_genome_dna.cpp:71]: Is the type change intentional? What if we keep it as `const interval_t&`? (still compiles and runs ok)

Comment (s22chan) [reply src/py_genome_dna.cpp:71]: either is fine (and basically equivalent) to the compiler since it's a read-only l-value
